import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";

const urbanistSans = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  display: "swap",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanistSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
